### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by selbstmacher** [PTST/LibreView-HomeAssistant#30]
It worked now for some months, but now I get the following error:
![Screenshot_20241120-121731](https://github.com/user-attachments/assets/59b6f242-fdc7-419a-8e0d-f974f0502f25)

**Comment by PTST** [comment]
Try switching to one of the eu servers under configure

If that doesn't work try and remove the configuration and set it up again

**Comment by riegera2412** [comment]
Not sure which country you are in. I am in Germany and according to another LibreLinkUp integration for Home Assistant facing the same problem, Abbott changed some header in the api to retrieve the data. ( https://github.com/gillesvs/librelink/issues/36#issue-2662624022 )

The guys over there are still trying to figure out what is wrong and how to fix it.

**Comment by PTST** [comment]
I'm personally on the eu servers which is not affected by this, so I would be trying to implement a fix blindly. 

I'm struggling with thinking of a way to fix this without someone with data on the German servers would have to share their info with me

If you are willing you could invite me to see your data?
If so please invite de-fix@steffensen.io
I will of course not keep any data and you can remove my access afterwards

**Comment by dreimer1986** [comment]
> Not sure which country you are in. I am in Germany and according to another LibreLinkUp integration for Home Assistant facing the same problem, Abbott changed some header in the api to retrieve the data. ( [gillesvs/librelink#36 (comment)](https://github.com/gillesvs/librelink/issues/36#issue-2662624022) )
> 
> The guys over there are still trying to figure out what is wrong and how to fix it.

Well, it's known what's wrong. The IO broker and Node Red solutions fixed it by adding account-ID to the headers. This entry includes a sha256-hash of the user ID.

**Comment by dreimer1986** [comment]
Switched over to this addin after I saw the expiry sensor I will use as morning reminder to bring a new one with me. COnfirmed working with Standard autodetection. Registered in Germany.

**Comment by PTST** [comment]
Great to hear that it's working again 👍

**Comment by sstawecki** [comment]
Hello! FYI, not working for me, after logging in with Global (I'm from Argentina)

```
2024-12-04 00:02:09.655 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry my@email.com for librelink
Traceback (most recent call last):
  File "/config/custom_components/librelink/api.py", line 200, in api_wrapper
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 430, message='', url='https://api.libreview.io/llu/auth/login'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/librelink/__init__.py", line 48, in async_setup_entry
    sessionToken = await myLibrelinkLogin.async_get_token()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/librelink/api.py", line 148, in async_get_token
    reponseLogin = await api_wrapper(
                   ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/librelink/api.py", line 209, in api_wrapper
    raise LibreLinkApiCommunicationError(
custom_components.librelink.api.LibreLinkApiCommunicationError: Error fetching information
```
